SELECT  ALIAS_0.CODIGO codigo, 
        ALIAS_0.DESCRIPCION descripcion, 
        ALIAS_0.INICIAL2_IMPORTE importe, 
        ALIAS_2.NOMBRE moneda, 
        ALIAS_3.NOMBRE unidad

FROM   V_PRECIO ALIAS_0  
LEFT JOIN V_CODIGOALTERNATIVO ALIAS_1 ON ALIAS_0.CODIGOALTERNATIVO_ID = ALIAS_1.ID   
LEFT JOIN V_UNIDADFINANCIERA ALIAS_2 ON ALIAS_0.VALOR2_UNIDADVALORIZACION_ID = ALIAS_2.ID   
LEFT JOIN V_UNIDADMEDIDA ALIAS_3 ON ALIAS_0.DCANTIDAD2_UNIDADMEDIDA_ID = ALIAS_3.ID   

WHERE ALIAS_0.BO_PLACE_ID = '{0724B015-1856-4450-8F59-07BC183F892E}'   
AND  ALIAS_0.ACTIVESTATUS <> 2