SELECT 
  A.ID, TIPO, 
  A.ESTADO, 
  A.NOTA AS LETRA, 
  A.NUMERODOCUMENTO, 
  A.FECHAACTUAL, 
	B.CODIGO AS COD_CLIENTE, 
  A.NOMBREDESTINATARIO AS NOM_CLIENTE, 
  G.CODIGO AS COD_COND_IVA, 
	G.NOMBRE AS NOM_COND_IVA, 
	(
    CASE 
      WHEN (C1.NUMERODOCUMETO <> '' and (valortotal >= 1000)) THEN C1.NUMERODOCUMETO
      WHEN (DNI<> '' and (valortotal >= 1000)) THEN DNI
       ELSE (CASE WHEN UPPER(PER.CUIT) = 'XX' THEN '-' ELSE PER.CUIT END)
       END
  ) CUIT, 
	(CASE WHEN A.ESTADO = 'N' OR A.NOMBREDESTINATARIO = 'Anulada' THEN 'Anulado' ELSE '' END) AS NOM_CLIENTE_ANULADA, 
	(CASE WHEN A.ESTADO = 'N' OR A.NOMBREDESTINATARIO = 'Anulada' THEN 'Anulado' ELSE '' END) AS CUIT_ANULADA, 
	(CASE WHEN A.ESTADO = 'N' OR A.NOMBREDESTINATARIO = 'Anulada' THEN 0 ELSE A.COTIZACION END) * (CASE WHEN A.TIPO = 'NC' THEN -1 ELSE 1 END) * A.VALORTOTAL AS TOTAL, 
	(CASE WHEN A.ESTADO = 'N' OR A.NOMBREDESTINATARIO = 'Anulada' THEN 0 ELSE A.COTIZACION END) * (CASE WHEN A.TIPO = 'NC' THEN -1 ELSE 1 END) * IVATASA.IMPORTE AS 
  IVA_TASA, 
	(CASE WHEN A.ESTADO = 'N' OR A.NOMBREDESTINATARIO = 'Anulada' THEN 0 ELSE A.COTIZACION END) * (CASE WHEN A.TIPO = 'NC' THEN -1 ELSE 1 END) * IVASOBRETASA.IMPORTE AS IVA_SOBRETASA, 
	(CASE WHEN A.ESTADO = 'N' OR A.NOMBREDESTINATARIO = 'Anulada' THEN 0 ELSE A.COTIZACION END) * (CASE WHEN A.TIPO = 'NC' THEN -1 ELSE 1 END) * 
  IVAPERCEPCION.IMPORTE AS IVA_PERCEPCION, 
	SUM
    (
      (CASE WHEN A.ESTADO = 'N' OR A.NOMBREDESTINATARIO = 'Anulada' THEN 0 ELSE A.COTIZACION END) * 
      (CASE WHEN A.TIPO = 'NC' THEN -1 ELSE 1 END) * 
      (CASE WHEN IPI.COEFICIENTE =.0000000000 THEN 1 ELSE 0 END) * 
      ITEM.TOTAL2_IMPORTE
    ) AS NETO_NO_GRAVADO_EXENTO, -- ver como tomar los exentos
	SUM
    (
      (CASE WHEN A.ESTADO = 'N' OR A.NOMBREDESTINATARIO = 'Anulada' THEN 0 ELSE A.COTIZACION END) * 
      (CASE WHEN A.TIPO = 'NC' THEN -1 ELSE 1 END) * 
      (CASE WHEN IPI.COEFICIENTE =.0000000000 THEN 0 ELSE 1 END) * 
      ITEM.TOTAL2_IMPORTE
    ) AS NETO_GRAVADO,
	((CASE WHEN A.ESTADO = 'N' OR A.NOMBREDESTINATARIO = 'Anulada' THEN 0 ELSE A.COTIZACION END) * 
	 (CASE WHEN A.TIPO = 'NC' THEN -1 ELSE 1 END) *	
	(SELECT SUM(VALOR.IMPORTE)
			FROM V_TOTALIZADORTRANSACCION TOT
	 		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID
	 		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID
			AND TOT.REFERENCIA_ID IN 
			(SELECT ID FROM V_IMPUESTO WHERE TIPO = 'PER' AND SUBTIPO = 'IIBB')
		)) AS IIBB,
	A.COTIZACION AS COTIZACION,
	A.NOMBREMONEDA AS MONEDA,
	SUM((CASE WHEN IPI.COEFICIENTE = 21 AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN CASE WHEN TIPO <> 'NC' 
				THEN 1
				ELSE 0 
				END
			ELSE 0 
			END) * VAL.IMPORTE * A.COTIZACION) AS IVA_21, 
	SUM((CASE WHEN IPI.COEFICIENTE = 27 AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN CASE WHEN TIPO <> 'NC' 
				THEN 1
				ELSE 0 
				END
			ELSE 0 
			END) * VAL.IMPORTE * A.COTIZACION) AS IVA_27, 
	SUM((CASE WHEN IPI.COEFICIENTE = 10.5 AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN CASE WHEN TIPO <> 'NC' 
				THEN 1
				ELSE 0 
				END
			ELSE 0 
			END) * VAL.IMPORTE * A.COTIZACION) AS IVA_10_5,
	SUM((CASE WHEN IPI.COEFICIENTE = 21 AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN CASE WHEN TIPO <> 'NC' 
				THEN 1
				ELSE 0 
				END
			ELSE 0 
			END) * ITEM.TOTAL2_IMPORTE * A.COTIZACION) AS NETO_21, 
	SUM((CASE WHEN IPI.COEFICIENTE = 27 AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN CASE WHEN TIPO <> 'NC' 
				THEN 1
				ELSE 0 
				END
			ELSE 0
			END) * ITEM.TOTAL2_IMPORTE * A.COTIZACION) AS NETO_27, 
	SUM((CASE WHEN IPI.COEFICIENTE = 10.5 AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN CASE WHEN TIPO <> 'NC' 
				THEN 1
				ELSE 0 
				END
			ELSE 0 
			END) * ITEM.TOTAL2_IMPORTE * A.COTIZACION) AS NETO_10_5,
	SUM(CASE WHEN IPI.COEFICIENTE = .0000000000 AND TIPO = 'NC' AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN ITEM.TOTAL2_IMPORTE * (-1) * A.COTIZACION
			ELSE 0 
			END) AS NCNETO_EX,
	SUM(CASE WHEN IPI.COEFICIENTE = 21 AND TIPO = 'NC' AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN ITEM.TOTAL2_IMPORTE * (-1) * A.COTIZACION
			ELSE 0 
			END) AS NCNETO_21,
	SUM(CASE WHEN IPI.COEFICIENTE = 10.5 AND TIPO = 'NC' AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN ITEM.TOTAL2_IMPORTE * (-1) * A.COTIZACION
			ELSE 0 
			END) AS NCNETO_105,
	SUM(CASE WHEN IPI.COEFICIENTE = 27 AND TIPO = 'NC' AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN ITEM.TOTAL2_IMPORTE * (-1) * A.COTIZACION
			ELSE 0 
			END) AS NCNETO_27,
	SUM(CASE WHEN IPI.COEFICIENTE = 21 AND TIPO = 'NC' AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO<>'Anulada'
			THEN VAL.IMPORTE * (-1) * A.COTIZACION
			ELSE 0 
			END) AS NCIVA_21,
	SUM(CASE WHEN IPI.COEFICIENTE = 10.5 AND TIPO = 'NC' AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN VAL.IMPORTE * (-1) * A.COTIZACION
			ELSE 0 
			END) AS NCIVA_105,
	SUM(CASE WHEN IPI.COEFICIENTE = 27 AND TIPO = 'NC' AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN VAL.IMPORTE * (-1) * A.COTIZACION
			ELSE 0 
			END) AS NCIVA_27,
	SUM(CASE WHEN IPI.COEFICIENTE = 21 AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN VAL.IMPORTE * A.COTIZACION * CASE WHEN TIPO = 'NC' THEN -1 ELSE 1 END
			ELSE 0 
			END) AS IVA21,
	SUM(CASE WHEN IPI.COEFICIENTE = 10.5 AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN VAL.IMPORTE * A.COTIZACION * CASE WHEN TIPO = 'NC' THEN -1 ELSE 1 END
			ELSE 0 
			END) AS IVA105,
	SUM(CASE WHEN IPI.COEFICIENTE = .0000000000 AND TIPO <> 'NC' AND A.ESTADO <> 'N' AND A.NOMBREDESTINATARIO <> 'Anulada'
			THEN ITEM.TOTAL2_IMPORTE * A.COTIZACION
			ELSE 0 
			END) AS NETO_EX
FROM (SELECT FV.ID, cast('FC' as varchar) AS TIPO, ESTADO, NOTA, NUMERODOCUMENTO, FECHAACTUAL, 
       (case when NOMBREDESTINATARIO = 'Salon de Ventas' and ((valortotal*cotizacion) > 1000) and tipotr.descripcion <> 'Anticipo' then coalesce(EXT.NOMBRECLIENTE,EXTMOST.NOMBRECLIENTE) else 

NOMBREDESTINATARIO end) NOMBREDESTINATARIO,
       COTIZACION, VALORTOTAL, DESTINATARIO_ID, UNIDADOPERATIVA_ID, ITEMSTRANSACCION_ID, SUBTOTAL_ID, TOTALES_ID, NOMBREMONEDA, 
       (case when tipotr.descripcion = 'Factura de Venta' then EXT.DNI else EXTMOST.DNI end) DNI

	       FROM V_TRFACTURAVENTA FV
		LEFT OUTER JOIN UD_TRFACTURAVENTA EXT ON FV.BOEXTENSION_ID = EXT.ID
		LEFT OUTER JOIN UD_TRFACTURAVENTAMOS EXTMOST ON FV.BOEXTENSION_ID = EXTMOST.ID
              LEFT OUTER JOIN UD_TRANTICIPO EXTANT ON FV.BOEXTENSION_ID = EXTANT.ID
		LEFT OUTER JOIN TIPOTRANSACCION TIPOTR ON TIPOTR.ID = FV.TIPOTRANSACCION_ID
		WHERE (EXT.FUEIMPRESA = TRUE or EXTMOST.FUEIMPRESA = TRUE or EXTANT.FUEIMPRESA = TRUE or FV.numerodocumentointerno <> '')
		--AND external_id <> 'ANULADA'
              and fv.numerodocumento not like '0011%'
		UNION ALL
		SELECT TR.ID, 'ND' AS TIPO, ESTADO, NOTA, NUMERODOCUMENTO, FECHAACTUAL, 
		(case when NOMBREDESTINATARIO = 'Salon de Ventas' and ((valortotal*cotizacion) > 1000) then EXT.NOMBRECLIENTE else NOMBREDESTINATARIO END) 

              NOMBREDESTINATARIO,
		COTIZACION, VALORTOTAL, DESTINATARIO_ID, 
		UNIDADOPERATIVA_ID, ITEMSTRANSACCION_ID, SUBTOTAL_ID, TOTALES_ID, NOMBREMONEDA, EXT.DNI DNI	
		FROM V_TRDEBITOVENTA TR
		LEFT OUTER JOIN UD_TRDEBITOVENTA EXT ON TR.BOEXTENSION_ID = EXT.ID
		WHERE TR.TIPOTRANSACCION_ID <> 'b0132ae0-b36b-47ab-956f-e3aac767a1ce' and numerodocumento like '0007%'
		UNION ALL
		SELECT TR.ID, 'NC' AS TIPO, TR.ESTADO, TR.NOTA, TR.NUMERODOCUMENTO, TR.FECHAACTUAL,
		(case when tr.NOMBREDESTINATARIO = 'Salon de Ventas' and ((tr.valortotal*tr.cotizacion) > 1000) then coalesce(EXT.NOMBRECLIENTE,vext.nombrecliente) else tr.NOMBREDESTINATARIO END) 
              NOMBREDESTINATARIO,
		TR.COTIZACION, TR.VALORTOTAL,TR.DESTINATARIO_ID, TR.UNIDADOPERATIVA_ID, TR.ITEMSTRANSACCION_ID, TR.SUBTOTAL_ID, 
		TR.TOTALES_ID, TR.NOMBREMONEDA, case when tr.tipotransaccion_id = '2d972a7e-568c-11d5-b612-0050dac017be' then coalesce(EXT.DNI,vext.DNI) else ext.dni end dni
		FROM V_TRCREDITOVENTA TR
		left outer join UD_TRNOTACREDITO ext on tr.boextension_id = ext.id
		left outer join v_trfacturaventa vtr on vtr.id = tr.vinculotr_id
		LEFT OUTER JOIN UD_TRFACTURAVENTAmos vEXT ON vtr.BOEXTENSION_ID = vEXT.ID
              WHERE --TR.TIPOTRANSACCION_ID <> '2d972a7e-568c-11d5-b612-0050dac017be' AND 
		tr.tipotransaccion_id <> 'fb21a160-794a-4a79-b311-e474eac3a43e'
		AND tr.external_id <> 'ANNULADA' and tr.numerodocumento not like '0011%'
	) A

	INNER JOIN V_CLIENTE B ON A.DESTINATARIO_ID = B.ID
	AND A.ESTADO ='C'
	AND (SELECT NOMBRE FROM V_UNIDADOPERATIVA UO
		WHERE UO.ID = A.UNIDADOPERATIVA_ID) NOT LIKE '%02%'
		AND SUBSTRING( A.FECHAACTUAL, 1, 8) >= SUBSTRING('20171201', 1, 8)
		AND SUBSTRING( A.FECHAACTUAL, 1, 8) <= SUBSTRING('20171231', 1, 8)
	LEFT OUTER JOIN V_PERSONAJURIDICA C ON B.ENTEASOCIADO_ID = C.ID
	LEFT OUTER JOIN V_PERSONAFISICA C1 ON B.ENTEASOCIADO_ID = C1.ID
       LEFT JOIN V_PERSONA PER ON B.ENTEASOCIADO_ID = PER.ID
--Posicion Del Cliente
	INNER JOIN V_POSICIONADORIMPUESTOS D ON B.POSICIONADORIMPUESTOS_ID = D.ID
	INNER JOIN V_ITEMPOSICIONADORIMPUESTOS E ON D.ITEMSPOSICIONADORIMPUESTOS_ID = E.BO_PLACE_ID
	INNER JOIN V_DEFINICIONIMPUESTO F ON E.DEFINICIONIMPUESTO_ID = F.ID
		AND F.IMPUESTO_ID = (SELECT ID FROM V_IMPUESTO WHERE NOMBRE = 'IVA TASA')
	INNER JOIN V_POSICIONIMPUESTO G ON E.POSICIONIMPUESTO_ID = G.ID
	INNER JOIN (SELECT BO_PLACE_ID, REFERENCIA_ID, IMPUESTOSITEMTRANSACCION_ID, NUMEROITEM, TOTAL2_IMPORTE
			 FROM V_ITEMFACTURAVENTA
			 UNION ALL
			 SELECT BO_PLACE_ID, REFERENCIA_ID, IMPUESTOSITEMTRANSACCION_ID, NUMEROITEM, TOTAL2_IMPORTE
			 FROM V_ITEMDEBITOVENTA
			 UNION ALL
			 SELECT BO_PLACE_ID, REFERENCIA_ID, IMPUESTOSITEMTRANSACCION_ID, NUMEROITEM, TOTAL2_IMPORTE
			 FROM V_ITEMCREDITOVENTA
		    ) ITEM ON A.ITEMSTRANSACCION_ID = ITEM.BO_PLACE_ID
	INNER JOIN (SELECT ID, POSICIONADORIMPUESTOS_ID FROM V_PRODUCTO
		     UNION ALL
		     SELECT ID, POSICIONADORIMPUESTOS_ID FROM V_SERVICIO
		     UNION ALL 
		     SELECT ID, POSICIONADORIMPUESTOS_ID FROM V_CONCEPTOCONTABLE
                  ) PRO ON ITEM.REFERENCIA_ID = PRO.ID
-- Posicion De Los Productos/Servicios/Concepto Contable
INNER JOIN V_POSICIONADORIMPUESTOS PI ON PRO.POSICIONADORIMPUESTOS_ID = PI.ID
INNER JOIN V_ITEMPOSICIONADORIMPUESTOS IPI ON PI.ITEMSPOSICIONADORIMPUESTOS_ID = IPI.BO_PLACE_ID
INNER JOIN V_DEFINICIONIMPUESTO DI ON IPI.DEFINICIONIMPUESTO_ID = DI.ID
	AND DI.IMPUESTO_ID = (SELECT ID FROM V_IMPUESTO WHERE NOMBRE = 'IVA TASA')
INNER JOIN V_POSICIONIMPUESTO PI2 ON IPI.POSICIONIMPUESTO_ID = PI2.ID
INNER JOIN V_IMPUESTOTRANSACCION IT ON ITEM.IMPUESTOSITEMTRANSACCION_ID = IT.BO_PLACE_ID
INNER JOIN V_VALOR VAL ON IT.VALOR_ID = VAL.ID
INNER JOIN V_VALOR SUBTOTAL ON A.SUBTOTAL_ID = SUBTOTAL.ID
LEFT JOIN V_TOTALIZADORTRANSACCION TOT ON A.TOTALES_ID = TOT.BO_PLACE_ID
	AND TOT.REFERENCIA_ID = (SELECT ID FROM V_IMPUESTO WHERE NOMBRE = 'IVA TASA')
LEFT JOIN V_VALOR IVATASA ON TOT.VALOR_ID = IVATASA.ID
LEFT JOIN V_TOTALIZADORTRANSACCION TOT2 ON A.TOTALES_ID = TOT2.BO_PLACE_ID 
	AND TOT2.REFERENCIA_ID = (SELECT ID FROM V_IMPUESTO WHERE NOMBRE = 'IVA Sobretasa')
LEFT JOIN V_VALOR IVASOBRETASA ON TOT2.VALOR_ID = IVASOBRETASA.ID 
LEFT JOIN V_TOTALIZADORTRANSACCION TOT3 ON A.TOTALES_ID = TOT3.BO_PLACE_ID 
	AND TOT3.REFERENCIA_ID = (SELECT ID FROM V_IMPUESTO WHERE NOMBRE = 'IVA Percepción')
LEFT JOIN V_VALOR IVAPERCEPCION ON TOT3.VALOR_ID = IVAPERCEPCION.ID 

GROUP BY A.ID, A.TIPO, A.ESTADO, A.NOTA, A.NUMERODOCUMENTO, A.FECHAACTUAL, 
	B.CODIGO, A.NOMBREDESTINATARIO, G.CODIGO, G.NOMBRE, 
      --(case when (DNI <> '' and (valortotal > 1000)) THEN DNI ELSE C.CUIT END), 
       (CASE WHEN (DNI <> '' and (valortotal > 1000)) THEN DNI 
        ELSE (CASE WHEN UPPER(PER.CUIT) = 'XX' THEN '' ELSE PER.CUIT END)
        END), 
	A.VALORTOTAL, IVATASA.IMPORTE, IVASOBRETASA.IMPORTE, IVAPERCEPCION.IMPORTE,
	SUBTOTAL.IMPORTE, -- Ver Como Tomar Los Exentos
	A.COTIZACION, A.NOMBREMONEDA, A.TOTALES_ID, A.NUMERODOCUMENTO,C1.NUMERODOCUMETO,A.DNI,PER.CUIT
ORDER BY A.FECHAACTUAL, TIPO, A.NOTA, A.NUMERODOCUMENTO 


