CREATE TEMPORARY TABLE DOCUMENTOSCOMPRAS
AS

SELECT A.ID, 
	cast('FC' as varchar) AS TIPO, 
	A.NUMERODOCUMENTO,
	A.NOTA AS LETRA, 
	TOTAL.IMPORTE AS TOTAL, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO WHERE NOMBRE = 'IVA TASA')
	) AS SOBRETASA, 
    (SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Buenos Aires')
	) AS PER_IB_BA, 
       (SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Capital Federal')
	)  AS PER_IB_CF, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Córdoba')
	)  AS PER_IB_COR, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Jujuy')
	)  AS PER_IB_JUJ, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Tucumán')
	)  AS PER_IB_TUC, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Tierra del Fuego')
	)  AS PER_IB_TDF, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Corrientes')
	)  AS PER_IB_CORR, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Rio Negro')
	)  AS PER_IB_RN, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Chaco')
	)  AS PER_IB_CHA, 
    (SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Chubut')
	) AS PER_IB_CHU, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Salta')
	) AS PER_IB_SAL, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Catamarca')
	) AS PER_IB_CAT, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Neuquén')
	) AS PER_IB_NEU, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Formosa')
	) AS PER_IB_FOR, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Santa Fe')
	) AS PER_IB_SFE, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción La Rioja')
	) AS PER_IB_LRIO,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Entre Ríos')
	) AS PER_IB_ER, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Mendoza')
	) AS PER_IB_MEN,
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción San Juan')
	) AS PER_IB_SJUAN,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción La Pampa')
	) AS PER_IB_LPAM,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'Impuestos Internos (Compras)')
	) AS IMPUESTOINT,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción San Luis')
	) AS PER_IB_SLUI,
 (SELECT SUM(VALOR.IMPORTE) FROM  V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE TIPO = 'PER' AND SUBTIPO = 'IVA')
    AND A.TIPOTRANSACCION_ID <> '{DF49E00D-DBE6-4976-9F7E-FCDC7AB0F842}'
	)  AS PER_IVA, 
(SELECT SUM(VALOR.IMPORTE) FROM  V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE TIPO = 'PER' AND SUBTIPO = 'IVA')
      AND A.TIPOTRANSACCION_ID = '{DF49E00D-DBE6-4976-9F7E-FCDC7AB0F842}'
	)  AS PER_IVA_ADUANA, 		
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
	WHERE TIPO = 'PER' AND SUBTIPO = 'GANANCIAS')
	) AS GANANCIAS, 
	--A.FECHAREGISTRO, 
	B.CODIGO AS COD_CLIENTE, 
	C.NOMBRE AS NOM_CLIENTE,
	C.CUIT AS CUIT,
	D2.CODIGO AS COD_COND_IVA, 
	D2.NOMBRE AS NOM_COND_IVA, 
	CASE WHEN A.COTIZACION = 0 AND MO.NOMBRE = 'Pesos' THEN 1 ELSE A.COTIZACION END COTIZACION,
	0 INTERESES ,
	0 GASTOS,
	0 IVA105,
	0 IVA21,
	SUBSTRING(A.FECHAREGISTRO,7,2) ||'/' ||SUBSTRING(A.FECHAREGISTRO,5,2) ||'/'||SUBSTRING(A.FECHAREGISTRO,1,4) AS FECHAREGISTRO,
	MO.NOMBRE MONEDA
FROM V_TRFACTURACOMPRA A
	INNER JOIN V_PROVEEDOR B ON A.DESTINATARIO_ID = B.ID 
	LEFT JOIN V_PERSONA C ON B.ENTEASOCIADO_ID = C.ID
	INNER JOIN V_POSICIONADORIMPUESTOS D ON B.POSICIONADORIMPUESTOS_ID = D.ID
	INNER JOIN V_ITEMPOSICIONADORIMPUESTOS D1 ON D.ITEMSPOSICIONADORIMPUESTOS_ID = D1.BO_PLACE_ID
	INNER JOIN V_DEFINICIONIMPUESTO DEF ON D1.DEFINICIONIMPUESTO_ID = DEF.ID
	  AND DEF.IMPUESTO_ID = '{89C2361A-3F01-11D5-86AD-0080AD403F5F}' --IVA TASA
	INNER JOIN V_POSICIONIMPUESTO D2 ON D1.POSICIONIMPUESTO_ID = D2.ID
	INNER JOIN V_VALOR TOTAL ON A.TOTAL_ID = TOTAL.ID
	LEFT JOIN V_MONEDA MO ON A.MONEDA_ID = MO.ID
WHERE  A.ESTADO = 'C'
  AND A.TIPOTRANSACCION_ID <>'{BD81D9CC-052C-11D6-8B40-0040335380BD}' -- Filtro de Provision de Factura de Gastos de Importacion	
  -- fecha
  AND SUBSTRING( A.FECHAREGISTRO, 1, 8) >= SUBSTRING('20171201', 1, 8)
  AND SUBSTRING( A.FECHAREGISTRO, 1, 8) <= SUBSTRING('20171231', 1, 8)
  AND A.EXTERNAL_ID = '';

--UNION ALL

INSERT INTO DOCUMENTOSCOMPRAS
SELECT	A.ID, 
	cast('NC' as varchar) AS TIPO, 
	A.NUMERODOCUMENTO,
	A.NOTA AS LETRA, 
       (-1) * TOTAL.IMPORTE AS TOTAL, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO WHERE NOMBRE = 'IVA TASA')
	)*(-1) AS SOBRETASA,
    (SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Buenos Aires')
	)*(-1) AS PER_IB_BA, 
       (SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Capital Federal')
	)*(-1)  AS PER_IB_CF, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Córdoba')
	)*(-1)  AS PER_IB_COR, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Jujuy')
	)*(-1)  AS PER_IB_JUJ, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Tucumán')
	)*(-1)  AS PER_IB_TUC, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Tierra del Fuego')
	)*(-1)  AS PER_IB_TDF, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Corrientes')
	)*(-1)  AS PER_IB_CORR, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Rio Negro')
	)*(-1)  AS PER_IB_RN, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Chaco')
	)*(-1)  AS PER_IB_CHA, 
    (SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Chubut')
	)*(-1) AS PER_IB_CHU, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Salta')
	)*(-1) AS PER_IB_SAL, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Catamarca')
	)*(-1) AS PER_IB_CAT, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Neuquén')
	)*(-1) AS PER_IB_NEU, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Formosa')
	)*(-1) AS PER_IB_FOR, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Santa Fe')
	)*(-1) AS PER_IB_SFE, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción La Rioja')
	)*(-1) AS PER_IB_LRIO,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Entre Ríos')
	)*(-1) AS PER_IB_ER, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Mendoza')
	)*(-1) AS PER_IB_MEN,
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción San Juan')
	)*(-1) AS PER_IB_SJUAN,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción La Pampa')
	)*(-1) AS PER_IB_LPAM,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'Impuestos Internos (Compras)')
	) AS IMPUESTOINT,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción San Luis')
	)*(-1) AS PER_IB_SLUI,
   (SELECT SUM(VALOR.IMPORTE) FROM  V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE TIPO = 'PER' AND SUBTIPO = 'IVA')
    AND A.TIPOTRANSACCION_ID <> '{DF49E00D-DBE6-4976-9F7E-FCDC7AB0F842}'
	)*(-1)  AS PER_IVA, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE TIPO = 'PER' AND SUBTIPO = 'IVA')
      AND A.TIPOTRANSACCION_ID = '{DF49E00D-DBE6-4976-9F7E-FCDC7AB0F842}'
	)*(-1)  AS PER_IVA_ADUANA, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
			WHERE TIPO = 'PER' AND SUBTIPO = 'GANANCIAS')
	) *(-1) AS GANANCIAS, 
	--A.FECHAREGISTRO, 
	B.CODIGO AS COD_CLIENTE, 
	C.NOMBRE AS NOM_CLIENTE,
	C.CUIT AS CUIT,
	D2.CODIGO AS COD_COND_IVA, 
	D2.NOMBRE AS NOM_COND_IVA, 
	CASE WHEN A.COTIZACION = 0 AND MO.NOMBRE = 'Pesos' THEN 1 ELSE A.COTIZACION END COTIZACION,
	0 INTERESES ,
	0 GASTOS,
	0 IVA105,
	0 IVA21,
	SUBSTRING(A.FECHAREGISTRO,7,2) ||'/' ||SUBSTRING(A.FECHAREGISTRO,5,2) ||'/'||SUBSTRING(A.FECHAREGISTRO,1,4) AS FECHAREGISTRO,
	MO.NOMBRE MONEDA

FROM V_TRCREDITOCOMPRA A
	INNER JOIN V_PROVEEDOR B ON A.DESTINATARIO_ID = B.ID
	LEFT JOIN V_PERSONA C ON B.ENTEASOCIADO_ID = C.ID
	INNER JOIN V_POSICIONADORIMPUESTOS D ON B.POSICIONADORIMPUESTOS_ID = D.ID
	INNER JOIN V_ITEMPOSICIONADORIMPUESTOS D1 ON D.ITEMSPOSICIONADORIMPUESTOS_ID = D1.BO_PLACE_ID
	INNER JOIN V_DEFINICIONIMPUESTO DEF ON D1.DEFINICIONIMPUESTO_ID = DEF.ID
	  AND DEF.IMPUESTO_ID = '{89C2361A-3F01-11D5-86AD-0080AD403F5F}' --IVA TASA
	INNER JOIN V_POSICIONIMPUESTO D2 ON D1.POSICIONIMPUESTO_ID = D2.ID
	INNER JOIN V_VALOR TOTAL ON A.TOTAL_ID = TOTAL.ID
	INNER JOIN V_TIPOTRANSACCION TT ON A.TIPOTRANSACCION_ID = TT.ID
		AND DESCRIPCION NOT LIKE '%interna%'
	LEFT JOIN V_MONEDA MO ON A.MONEDA_ID = MO.ID

WHERE  A.ESTADO = 'C'
  	AND A.TIPOTRANSACCION_ID <> '{2459D51A-6500-4412-A060-9AED50DB47DF}' -- Filtro Saldos Iniciales Proveedores Acreedor
	AND A.TIPOTRANSACCION_ID <> '{305C431B-5CDE-4C8D-900E-E21D7EEDEEB9}'-- Filtro Rendicion de Gastos 
       AND A.TIPOTRANSACCION_ID <> 'd87c9596-63cb-44bf-93fb-6812f2e66c26' -- ND Anulada
	AND A.tipotransaccion_id <> '33587f62-2a8d-4279-ad44-5c2502e7dc3b' -- NC INT
    -- fecha
	AND SUBSTRING( A.FECHAREGISTRO, 1, 8) >= SUBSTRING('20171201', 1, 8)
	AND SUBSTRING( A.FECHAREGISTRO, 1, 8) <= SUBSTRING('20171231', 1, 8)
	AND A.NOMBRE NOT LIKE  'Fact.Anul.%'
	AND A.EXTERNAL_ID = '';
	--AND A.NUMERODOCUMENTO NOT LIKE '7%'
	--AND A.NUMERODOCUMENTO NOT LIKE '8%'
	--AND A.NUMERODOCUMENTO NOT LIKE '9%'
	--AND A.NUMERODOCUMENTO NOT LIKE ''
	
	--and a.flag_id = 'e1caa956-81c1-11d5-8708-0080ad403f5f';
--UNION ALL

INSERT INTO DOCUMENTOSCOMPRAS
SELECT A.ID, 
	cast('ND' as varchar) AS TIPO, 
        A.NUMERODOCUMENTO,
	A.NOTA AS LETRA, 
       TOTAL.IMPORTE AS TOTAL, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO WHERE NOMBRE = 'IVA TASA')
	) AS SOBRETASA,
	 (SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Buenos Aires')
	) AS PER_IB_BA, 
       (SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Capital Federal')
	)  AS PER_IB_CF, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Córdoba')
	)  AS PER_IB_COR, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Jujuy')
	)  AS PER_IB_JUJ, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Tucumán')
	)  AS PER_IB_TUC, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Tierra del Fuego')
	)  AS PER_IB_TDF, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Corrientes')
	)  AS PER_IB_CORR, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Rio Negro')
	)  AS PER_IB_RN, 
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
		LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
		WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
		AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Chaco')
	)  AS PER_IB_CHA, 
    (SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Chubut')
	) AS PER_IB_CHU, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Salta')
	) AS PER_IB_SAL, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Catamarca')
	) AS PER_IB_CAT, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Neuquén')
	) AS PER_IB_NEU, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Formosa')
	) AS PER_IB_FOR, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Santa Fe')
	) AS PER_IB_SFE, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción La Rioja')
	) AS PER_IB_LRIO,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Entre Ríos')
	) AS PER_IB_ER, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción Mendoza')
	) AS PER_IB_MEN,
	(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción San Juan')
	) AS PER_IB_SJUAN,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción La Pampa')
	) AS PER_IB_LPAM,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'Impuestos Internos (Compras)')
	) AS IMPUESTOINT,
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE NOMBRE = 'IIBB Percepción San Luis')
	) AS PER_IB_SLUI,
    (SELECT SUM(VALOR.IMPORTE) FROM  V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE TIPO = 'PER' AND SUBTIPO = 'IVA')
    AND A.TIPOTRANSACCION_ID <> '{DF49E00D-DBE6-4976-9F7E-FCDC7AB0F842}'
	)  AS PER_IVA, 
(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE TIPO = 'PER' AND SUBTIPO = 'IVA')
      AND A.TIPOTRANSACCION_ID = '{DF49E00D-DBE6-4976-9F7E-FCDC7AB0F842}'
	)  AS PER_IVA_ADUANA, 
		(SELECT SUM(VALOR.IMPORTE) FROM V_TOTALIZADORTRANSACCION TOT
	LEFT JOIN V_VALOR VALOR ON TOT.VALOR_ID = VALOR.ID 
	WHERE A.TOTALES_ID = TOT.BO_PLACE_ID 
	  AND TOT.REFERENCIA_ID IN (SELECT ID FROM V_IMPUESTO
					WHERE TIPO = 'PER' AND SUBTIPO = 'GANANCIAS')
	) AS GANANCIAS, 
	--A.FECHAREGISTRO, 
	B.CODIGO AS COD_CLIENTE, 
	C.NOMBRE AS NOM_CLIENTE,
    C.CUIT AS CUIT,
    D2.CODIGO AS COD_COND_IVA, D2.NOMBRE AS NOM_COND_IVA,  
	CASE WHEN A.COTIZACION = 0 AND MO.NOMBRE = 'Pesos' THEN 1 ELSE A.COTIZACION END COTIZACION,
	0 INTERESES ,
	0 GASTOS,
	0 IVA105,
	0 IVA21,
	SUBSTRING(A.FECHAREGISTRO,7,2) ||'/' ||SUBSTRING(A.FECHAREGISTRO,5,2) ||'/'||SUBSTRING(A.FECHAREGISTRO,1,4) AS FECHAREGISTRO,
	MO.NOMBRE MONEDA
FROM V_TRDEBITOCOMPRA A
	INNER JOIN V_PROVEEDOR B ON A.DESTINATARIO_ID = B.ID
	LEFT JOIN V_PERSONA C ON B.ENTEASOCIADO_ID = C.ID
	INNER JOIN V_POSICIONADORIMPUESTOS D ON B.POSICIONADORIMPUESTOS_ID = D.ID
	INNER JOIN V_ITEMPOSICIONADORIMPUESTOS D1 ON D.ITEMSPOSICIONADORIMPUESTOS_ID=D1.BO_PLACE_ID
	INNER JOIN V_DEFINICIONIMPUESTO DEF ON D1.DEFINICIONIMPUESTO_ID = DEF.ID
  	   AND DEF.IMPUESTO_ID = '{89C2361A-3F01-11D5-86AD-0080AD403F5F}' --IVA TASA
	INNER JOIN V_POSICIONIMPUESTO D2 ON D1.POSICIONIMPUESTO_ID = D2.ID
	INNER JOIN V_VALOR TOTAL ON A.TOTAL_ID = TOTAL.ID
	INNER JOIN V_TIPOTRANSACCION TT ON A.TIPOTRANSACCION_ID = TT.ID
	   AND DESCRIPCION NOT LIKE '%interna%'
	LEFT JOIN V_MONEDA MO ON A.MONEDA_ID=MO.ID
WHERE A.ESTADO = 'C'
	and a.tipotransaccion_id <> '27A38EB3-2B6E-436B-9A89-E21FD99186ED'   -- ND INT
	AND A.TIPOTRANSACCION_ID <> '{ADD38B77-71F2-431A-A327-F65F26EC6239}' -- Filtro Saldos Iniciales Proveedores Deudor
	AND A.TIPOTRANSACCION_ID <> '34bcb28c-874b-47ac-9a80-b1a7fdda0d7c'   -- NC ANULADA
	AND A.nombre not like '%NC.Anul.%'						-- NC ANULADA
    -- fecha
	AND SUBSTRING( A.FECHAREGISTRO, 1, 8) >= SUBSTRING('20171201', 1, 8)
	AND SUBSTRING( A.FECHAREGISTRO, 1, 8) <= SUBSTRING('20171231', 1, 8) 
	AND A.EXTERNAL_ID = ''
	AND A.NOMBRE NOT LIKE 'NDAgente%';

--UNION ALL

INSERT INTO DOCUMENTOSCOMPRAS
SELECT
EV.ID,
 cast('GastosRCC' as varchar) AS TIPO, 
      EV.NUMERODOCUMENTO,
	'' AS LETRA, 
	0 AS TOTAL, 
	0 AS SOBRETASA,
	0 AS PER_IB_BA,
	0 AS PER_IB_CF,
	0 AS PER_IB_COR,
	0 AS PER_IB_JUJ,
	0 AS PER_IB_TUC,
	0 AS PER_IB_TDF,
	0 AS PER_IB_CORR,
	0 AS PER_IB_RN, 
	0 AS PER_IB_CHA,
	0 AS PER_IB_CHU, 
	0 AS PER_IB_SAL, 
	0 AS PER_IB_CAT, 
	0 AS PER_IB_NEU, 
	0 AS PER_IB_FOR, 
	0 AS PER_IB_SFE, 
	0 AS PER_IB_LRIO,
	0 AS PER_IB_ER, 
	0 AS PER_IB_MEN,
	0 AS PER_IB_SJUAN,
	0 AS PER_IB_LPAM,
	0 AS IMPUESTOINT,
	0 AS PER_IB_SLUI,
	0 AS PER_IVA, 
    0 AS PER_IVA_ADUANA,
	0 AS GANANCIAS,
    --  FECHAREGISTRO,
      '' AS COD_CLIENTE, 
	BANCO.ENTEASOCIADOSUCURSAL AS NOM_CLIENTE,
      CASE WHEN PER.CUIT = 'xx' THEN '' ELSE PER.CUIT END CUIT ,
      '' AS COD_COND_IVA, '' AS NOM_COND_IVA, 
	CASE WHEN EV.COTIZACION =  0 AND MO.NOMBRE = 'Pesos' THEN 1 ELSE EV.COTIZACION END COTIZACION,
	CASE WHEN IC.NOMBRE LIKE 'Intereses por Cesión de Factura%' THEN ITEMEV.VALOR2_IMPORTE ELSE 0 END INTERESES ,
	CASE WHEN IC.NOMBRE LIKE 'Gastos por Cesión de Factura%' THEN ITEMEV.VALOR2_IMPORTE ELSE 0 END GASTOS,
	CASE IC.NOMBRE WHEN 'IVA Compras (10,5%)' THEN ITEMEV.VALOR2_IMPORTE ELSE 0 END IVA105,
	CASE IC.NOMBRE WHEN 'IVA Compras (21%)' THEN ITEMEV.VALOR2_IMPORTE ELSE 0 END IVA21,
	SUBSTRING(EV.FECHAACTUAL,7,2) ||'/' ||SUBSTRING(EV.FECHAACTUAL,5,2) ||'/'||SUBSTRING(EV.FECHAACTUAL,1,4) AS FECHAREGISTRO,
	MO.NOMBRE MONEDA

FROM V_TREGRESOVALORES EV
	JOIN V_ITEMEGRESOVALORES ITEMEV ON EV.ITEMSTRANSACCION_ID = ITEMEV.BO_PLACE_ID
	JOIN V_TIPOTRANSACCION TIPO ON EV.TIPOTRANSACCION_ID = TIPO.ID 
	JOIN V_CUENTABANCARIA CUENTA ON EV.ORIGINANTE_ID = CUENTA.ID
	JOIN V_BANCO BANCO ON CUENTA.BANCO_ID = BANCO.ID
	JOIN V_PERSONAJURIDICA PER ON BANCO.ENTEASOCIADO_ID = PER.ID
	JOIN V_IMPUTACIONCONTABLE IC ON ITEMEV.IMPUTACIONCONTABLE_ID = IC.ID
	LEFT JOIN V_MONEDA MO ON EV.MONEDA_ID = MO.ID

WHERE TIPO.DESCRIPCION = 'Gastos por Cesión'
	AND SUBSTRING( EV.FECHAACTUAL, 1, 8) >= SUBSTRING('20171201', 1, 8)
	AND SUBSTRING( EV.FECHAACTUAL, 1, 8) <= SUBSTRING('20171231', 1, 8)
	AND EV.ESTADO = 'C'	
	AND EV.EXTERNAL_ID = '';


SELECT 
	ID AS TRID, 
	TIPO, 
	NUMERODOCUMENTO, 
	LETRA,	
	TOTAL * COTIZACION AS TOTAL, 
	NULLIF( SOBRETASA, 0)*COTIZACION AS SOBRETASA,
	NULLIF( PER_IB_BA, 0)*COTIZACION AS PER_IB_BA,
	NULLIF( PER_IB_CF, 0)*COTIZACION AS PER_IB_CF,
	NULLIF( PER_IB_COR, 0)*COTIZACION AS PER_IB_COR,
	NULLIF( PER_IB_JUJ, 0)*COTIZACION AS PER_IB_JUJ,
	NULLIF( PER_IB_TUC, 0)*COTIZACION AS PER_IB_TUC,
	NULLIF( PER_IB_TDF, 0)*COTIZACION AS PER_IB_TDF,
	NULLIF( PER_IB_CORR, 0)*COTIZACION AS PER_IB_CORR,
	NULLIF( PER_IB_RN, 0)*COTIZACION AS PER_IB_RN,
	NULLIF( PER_IB_CHA, 0)*COTIZACION AS PER_IB_CHA,
	NULLIF( PER_IB_CHU, 0)*COTIZACION AS PER_IB_CHU, 
	NULLIF( PER_IB_SAL, 0)*COTIZACION AS PER_IB_SAL, 
	NULLIF( PER_IB_CAT, 0)*COTIZACION AS PER_IB_CAT, 
	NULLIF( PER_IB_NEU, 0)*COTIZACION AS PER_IB_NEU, 
	NULLIF( PER_IB_FOR, 0)*COTIZACION AS PER_IB_FOR, 
	NULLIF( PER_IB_SFE, 0)*COTIZACION AS PER_IB_SFE, 
	NULLIF( PER_IB_LRIO, 0)*COTIZACION AS PER_IB_LRIO,
	NULLIF( PER_IB_ER, 0)*COTIZACION AS PER_IB_ER, 
	NULLIF( PER_IB_MEN, 0)*COTIZACION AS PER_IB_MEN,
	NULLIF( PER_IB_SJUAN, 0)*COTIZACION AS PER_IB_SJUAN,
	NULLIF( PER_IB_LPAM, 0)*COTIZACION AS PER_IB_LPAM,
	NULLIF( IMPUESTOINT, 0)*COTIZACION AS IMPUESTOINT,
	NULLIF( PER_IB_SLUI, 0)*COTIZACION AS PER_IB_SLUI,
	NULLIF( PER_IVA, 0)*COTIZACION AS PER_IVA,
    NULLIF( PER_IVA_ADUANA, 0)*COTIZACION AS PER_IVA_ADUANA,
	NULLIF( GANANCIAS, 0)*COTIZACION AS GANANCIAS,
FECHAREGISTRO,
 	COD_CLIENTE, 
	NOM_CLIENTE, 
	CUIT, 
	COD_COND_IVA, 
	NOM_COND_IVA,
	COTIZACION,
	MONEDA,
	NULLIF( PER_IB_BA, 0)*COTIZACION +
	NULLIF( PER_IB_CF, 0)*COTIZACION +
	NULLIF( PER_IB_COR, 0)*COTIZACION +
	NULLIF( PER_IB_JUJ, 0)*COTIZACION +
	NULLIF( PER_IB_TUC, 0)*COTIZACION +
	NULLIF( PER_IB_TDF, 0)*COTIZACION +
	NULLIF( PER_IB_CORR, 0)*COTIZACION +
	NULLIF( PER_IB_RN, 0)*COTIZACION +
	NULLIF( PER_IB_CHA, 0)*COTIZACION +
	NULLIF( PER_IB_CHU, 0)*COTIZACION +
	NULLIF( PER_IB_SAL, 0)*COTIZACION +
	NULLIF( PER_IB_CAT, 0)*COTIZACION +
	NULLIF( PER_IB_NEU, 0)*COTIZACION +
	NULLIF( PER_IB_FOR, 0)*COTIZACION +
	NULLIF( PER_IB_SFE, 0)*COTIZACION +
	NULLIF( PER_IB_LRIO, 0)*COTIZACION +
	NULLIF( PER_IB_ER, 0)*COTIZACION + 
	NULLIF( PER_IB_MEN, 0)*COTIZACION +
	NULLIF( PER_IB_SJUAN, 0)*COTIZACION +
	NULLIF( PER_IB_LPAM, 0)*COTIZACION +
	NULLIF( IMPUESTOINT, 0)*COTIZACION +
	NULLIF( PER_IB_SLUI, 0)*COTIZACION AS TOTALPERIB
FROM  DOCUMENTOSCOMPRAS
GROUP BY ID, TIPO, NUMERODOCUMENTO, COD_CLIENTE, NOM_CLIENTE, TOTAL,
PER_IB_BA, PER_IB_CF, PER_IB_COR, PER_IB_JUJ, PER_IB_TUC, PER_IB_TDF, 
PER_IB_CORR, PER_IB_RN, PER_IB_CHA, PER_IB_CHU, PER_IB_SAL, PER_IB_CAT, 
PER_IB_NEU, PER_IB_FOR, PER_IB_SFE, PER_IB_LRIO, PER_IB_ER, PER_IB_MEN, 
PER_IB_SJUAN,
PER_IB_LPAM,
IMPUESTOINT, 
PER_IB_SLUI, PER_IVA, PER_IVA_ADUANA,SOBRETASA, GANANCIAS, CUIT, COD_COND_IVA, NOM_COND_IVA, 
COTIZACION, MONEDA, LETRA, FECHAREGISTRO

ORDER BY FECHAREGISTRO, TIPO, NUMERODOCUMENTO, COD_CLIENTE, NOM_CLIENTE


