SELECT			SUBSTRING(I_CONTABLE.fechavencimiento,1,4)||'/'|| SUBSTRING(I_CONTABLE.fechavencimiento,5,2) ||'/'|| SUBSTRING(I_CONTABLE.fechavencimiento,7,2) FECHA_ENTREGA, 
  				CUENTA.CODIGO CODIGO_CUENTA, 
					I_CONTABLE.DESCRIPCION NOMBRE_CUENTA, 
					(I_CONTABLE.DEBE2_IMPORTE - I_CONTABLE.HABER2_IMPORTE) SALDO,
					I_CONTABLE.DEBE2_IMPORTE DEBE,
					I_CONTABLE.HABER2_IMPORTE HABER,
					TR_CONTABLE.NOMBREDESTINATARIO DESTINATARIO,
					TR_CONTABLE.NOMBREORIGINANTE ORIGINANTE,
					I_CONTABLE.NOMBRETR ASIENTO,
					TR_CONTABLE.DETALLE DETALLE,
					-- IC.NOMBRE TIPOGANANCIA,
					C_COSTOS.NOMBRE C_COSTOS
-- 				IC1.NOMBRE TIPOMOVIMIENTO,
-- 				IC2.NOMBRE TIPOGASTO,

FROM  				V_ITEMCONTABLE I_CONTABLE 
LEFT JOIN 		V_TRCONTABLE TR_CONTABLE ON I_CONTABLE.PLACEOWNER_ID = TR_CONTABLE.ID
LEFT JOIN 		V_CUENTA CUENTA ON I_CONTABLE.REFERENCIA_ID = CUENTA.ID  
LEFT JOIN 		V_UD_CUENTACONTABLE CUENTA_CONT ON CUENTA_CONT.ID = CUENTA.BOEXTENSION_ID
LEFT JOIN 		V_ITEMTIPOCLASIFICADOR IC ON CUENTA_CONT.TIPOGANANCIA_ID = IC.ID
LEFT JOIN 		V_CENTROCOSTOS C_COSTOS ON I_CONTABLE.CENTROCOSTOS_ID = C_COSTOS.ID

WHERE 			I_CONTABLE.BO_PLACE_ID IS NOT NULL 
-- AND		 			SUBSTRING(I_CONTABLE.FECHAVENCIMIENTO,1,8) >= SUBSTRING('20190101',1,8)
-- AND 				SUBSTRING(I_CONTABLE.FECHAVENCIMIENTO,1,8) <= SUBSTRING('20190604',1,8)
AND		 			SUBSTRING(I_CONTABLE.FECHAVENCIMIENTO,1,8) >= ${fechaDesde} 
AND		 			SUBSTRING(I_CONTABLE.FECHAVENCIMIENTO,1,8) <= ${fechaHasta}
AND 				IC.NOMBRE not like ''
AND 				(I_CONTABLE.ESTADOTR = 'A' OR I_CONTABLE.ESTADOTR = 'C') 

ORDER BY 		FECHA_ENTREGA DESC